import type {
  DataSourceDefinition,
  ReportFieldDefinition,
  FilterOperator,
} from "../types";

// Filter operators by field type
export const FILTER_OPERATORS_BY_TYPE: Record<
  string,
  { value: FilterOperator; label: string }[]
> = {
  string: [
    { value: "equals", label: "Equals" },
    { value: "not_equals", label: "Does not equal" },
    { value: "contains", label: "Contains" },
    { value: "not_contains", label: "Does not contain" },
    { value: "starts_with", label: "Starts with" },
    { value: "ends_with", label: "Ends with" },
    { value: "is_empty", label: "Is empty" },
    { value: "is_not_empty", label: "Is not empty" },
  ],
  number: [
    { value: "equals", label: "Equals" },
    { value: "not_equals", label: "Does not equal" },
    { value: "greater_than", label: "Greater than" },
    { value: "less_than", label: "Less than" },
    { value: "greater_than_or_equal", label: "Greater than or equal" },
    { value: "less_than_or_equal", label: "Less than or equal" },
    { value: "between", label: "Between" },
    { value: "is_empty", label: "Is empty" },
    { value: "is_not_empty", label: "Is not empty" },
  ],
  date: [
    { value: "on_date", label: "On date" },
    { value: "before", label: "Before" },
    { value: "after", label: "After" },
    { value: "between", label: "Between" },
    { value: "is_empty", label: "Is empty" },
    { value: "is_not_empty", label: "Is not empty" },
  ],
  datetime: [
    { value: "on_date", label: "On date" },
    { value: "before", label: "Before" },
    { value: "after", label: "After" },
    { value: "between", label: "Between" },
    { value: "is_empty", label: "Is empty" },
    { value: "is_not_empty", label: "Is not empty" },
  ],
  boolean: [{ value: "equals", label: "Is" }],
  enum: [
    { value: "equals", label: "Equals" },
    { value: "not_equals", label: "Does not equal" },
    { value: "in", label: "Is any of" },
    { value: "not_in", label: "Is none of" },
  ],
  relation: [
    { value: "equals", label: "Equals" },
    { value: "not_equals", label: "Does not equal" },
    { value: "contains", label: "Contains" },
    { value: "is_empty", label: "Is empty" },
    { value: "is_not_empty", label: "Is not empty" },
  ],
};

// Incidents Data Source Fields
export const incidentFields: ReportFieldDefinition[] = [
  {
    field: "id",
    label: "id",
    label_ar: "معرف",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "workflow_transition_name",
    label: "Transition Name",
    label_ar: "اسم الانتقال",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "workflow_transition_id",
    label: "Transition",
    label_ar: "الانتقال",
    type: "enum",
    dynamicOptions: "transitions",
    multiselect: true,
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "workflow_transition_at",
    label: "Transition At",
    label_ar: "وقت الانتقال",
    type: "date",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reopen1_at",
    label: "Reopened Date",
    label_ar: "تاريخ إعادة الفتح",
    type: "date",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "incident_number",
    label: "Incident Number",
    label_ar: "رقم الحادث",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "title",
    label: "Title",
    label_ar: "العنوان",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "description",
    label: "Description",
    label_ar: "الوصف",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "priority",
    label: "Priority",
    label_ar: "الأولوية",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    options: [
      { value: 1, label: "Critical" },
      { value: 2, label: "High" },
      { value: 3, label: "Medium" },
      { value: 4, label: "Low" },
      { value: 5, label: "Minimal" },
    ],
  },
  {
    field: "severity",
    label: "Severity",
    label_ar: "الخطورة",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    options: [
      { value: 1, label: "Critical" },
      { value: 2, label: "High" },
      { value: 3, label: "Medium" },
      { value: 4, label: "Low" },
      { value: 5, label: "Minimal" },
    ],
  },
  {
    field: "reopen1_comment",
    label: "Reopened1 comment",
    label_ar: "تعليق إعادة الفتح 1",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reopen1_feedback",
    label: "Reopened Feedback",
    label_ar: "ملاحظات إعادة الفتح",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "assignee_id",
    label: "Assignee",
    label_ar: "المكلّف",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
  },
  {
    field: "classification_id",
    label: "Classification",
    label_ar: "التصنيف",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "classifications",
    canBeColumn: false,
    multiselect: true,
  },
  {
    field: "department_id",
    label: "Department",
    label_ar: "القسم",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "departments",
    canBeColumn: false,
  },
  {
    field: "location_id",
    label: "Location",
    label_ar: "الموقع",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "locations",
    canBeColumn: false,
    multiselect: true,
  },
  {
    field: "latitude",
    label: "Latitude",
    label_ar: "خط العرض",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
  },
  {
    field: "longitude",
    label: "Longitude",
    label_ar: "خط الطول",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
  },
  {
    field: "due_date",
    label: "Due Date",
    label_ar: "تاريخ الاستحقاق",
    type: "date",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "resolved_at",
    label: "Resolved At",
    label_ar: "تاريخ الحل",
    type: "date",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "closed_at",
    label: "Closed At",
    label_ar: "تاريخ الإغلاق",
    type: "date",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "sla_breached",
    label: "Sla Breached",
    label_ar: "تم تجاوز اتفاقية مستوى الخدمة",
    type: "boolean",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "sla_deadline",
    label: "Sla Deadline",
    label_ar: "موعد اتفاقية مستوى الخدمة",
    type: "date",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reporter_phone",
    label: "Reporter Phone",
    label_ar: "هاتف المبلّغ",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reporter_id",
    label: "Reporter",
    label_ar: "المبلّغ",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
  },
  {
    field: "reporter_email",
    label: "Reporter Email",
    label_ar: "البريد الإلكتروني للمبلّغ",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reporter_name",
    label: "Reporter Name",
    label_ar: "اسم المبلّغ",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },

  {
    field: "feedbacks",
    label: "Feedbacks",
    label_ar: "التقييمات",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "feedback_array",
    label: "Feedback array",
    label_ar: "مصفوفة التقييمات",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },

  {
    field: "closed_feedback",
    label: "Closed feedback",
    label_ar: "ملاحظات الإغلاق",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "rejected_feedback",
    label: "Rejected feedback",
    label_ar: "ملاحظات الرفض",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "under_resolution_feedback",
    label: "Under resolution feedback",
    label_ar: "ملاحظات قيد المعالجة",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "ready_to_close_feedback",
    label: "Ready to close feedback",
    label_ar: "ملاحظات جاهز للإغلاق",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reopened_feedback",
    label: "Reopened feedback",
    label_ar: "ملاحظات إعادة الفتح",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },

  {
    field: "closed_comment",
    label: "Closed comment",
    label_ar: "تعليق الإغلاق",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "rejected_comment",
    label: "Rejected comment",
    label_ar: "تعليق الرفض",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "under_resolution_comment",
    label: "Under resolution comment",
    label_ar: "تعليق قيد المعالجة",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "ready_to_close_comment",
    label: "Ready to close comment",
    label_ar: "تعليق جاهز للإغلاق",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reopened_comment",
    label: "Reopened comment",
    label_ar: "تعليق إعادة الفتح",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },

  {
    field: "full_location",
    label: "Full location",
    label_ar: "الموقع الكامل",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "full_classification",
    label: "Full classification",
    label_ar: "التصنيف الكامل",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
    multiselect: true,
  },

  {
    field: "reopen1_comment",
    label: "Reopened1 comment",
    label_ar: "تعليق إعادة الفتح 1",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reopen1_feedback",
    label: "Reopened1 Feedback",
    label_ar: "ملاحظات إعادة الفتح 1",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },

  // { field: "custom_fields", label: "Custom Fields", type: "string", category: "Core", sortable: true, filterable: true },
  {
    field: "created_at",
    label: "Created At",
    label_ar: "تاريخ الإنشاء",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "updated_at",
    label: "Updated At",
    label_ar: "تاريخ التحديث",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "deleted_at",
    label: "Deleted At",
    label_ar: "تاريخ الحذف",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "record_type",
    label: "Record Type",
    label_ar: "نوع السجل",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "source_incident_id",
    label: "Source Incident Id",
    label_ar: "معرف الحادث المصدر",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "converted_request_id",
    label: "Converted Request Id",
    label_ar: "معرف الطلب المحول",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "channel",
    label: "Channel",
    label_ar: "القناة",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    multiselect: true,
    options: [
      { value: "web", label: "Web Portal" },
      { value: "mobile", label: "Mobile App" },
      { value: "email", label: "Email" },
      { value: "phone", label: "Phone" },
      { value: "walk_in", label: "Walk-in" },
      { value: "api", label: "API Integration" },
      { value: "social_media", label: "Social Media" },
      { value: "940_system", label: "940 System" },
      { value: "940_manual", label: "940 Manual" },
      { value: "field", label: "Field" },
      { value: "manual", label: "Manual Entry" },
      { value: "other", label: "Other" },
    ],
  },
  {
    field: "created_by_id",
    label: "Created By",
    label_ar: "أُنشئ بواسطة",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
  },
  {
    field: "created_by_name",
    label: "Created By Name",
    label_ar: "اسم المنشئ",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "name",
  },
  {
    field: "created_by_mobile",
    label: "Created By Mobile",
    label_ar: "هاتف المنشئ",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "mobile",
  },
  {
    field: "evaluation_count",
    label: "Evaluation Count",
    label_ar: "عدد التقييمات",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "address",
    label: "Address",
    label_ar: "العنوان",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "city",
    label: "City",
    label_ar: "المدينة",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "state",
    label: "State",
    label_ar: "الولاية",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "country",
    label: "Country",
    label_ar: "الدولة",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "postal_code",
    label: "Postal Code",
    label_ar: "الرمز البريدي",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "source",
    label: "Channel",
    label_ar: "القناة",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    multiselect: true,
    options: [
      { value: "web", label: "Web Portal" },
      { value: "mobile", label: "Mobile App" },
      { value: "email", label: "Email" },
      { value: "phone", label: "Phone" },
      { value: "walk_in", label: "Walk-in" },
      { value: "api", label: "API Integration" },
      { value: "social_media", label: "Social Media" },
      { value: "940_system", label: "940 System" },
      { value: "940_manual", label: "940 Manual" },
      { value: "field", label: "Field" },
      { value: "manual", label: "Manual Entry" },
      { value: "other", label: "Other" },
    ],
  },
  {
    field: "version",
    label: "Version",
    label_ar: "الإصدار",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "master_incident_id",
    label: "Master Incident Id",
    label_ar: "معرف الحادث الرئيسي",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "is_merged",
    label: "Is Merged",
    label_ar: "تم الدمج",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "merged_at",
    label: "Merged At",
    label_ar: "تاريخ الدمج",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "merged_by_user_id",
    label: "Merged By User",
    label_ar: "تم الدمج بواسطة المستخدم",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "source_incident_ids",
    label: "Source Incident Ids",
    label_ar: "معرفات الحوادث المصدر",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "ready_to_close_expires_at",
    label: "Ready To Close Expires At",
    label_ar: "انتهاء الجاهزية للإغلاق",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "ready_to_close_duration",
    label: "Ready To Close Duration",
    label_ar: "مدة الجاهزية للإغلاق",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "ready_to_close_notified",
    label: "Ready To Close Notified",
    label_ar: "تم إشعار الجاهزية للإغلاق",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reporter_first_name",
    label: "Reporter First Name",
    label_ar: "الاسم الأول للمبلّغ",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reporter_last_name",
    label: "Reporter Last Name",
    label_ar: "اسم العائلة للمبلّغ",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reporter_username",
    label: "Reporter Username",
    label_ar: "اسم المستخدم للمبلّغ",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "assignee_email",
    label: "Assignee Email",
    label_ar: "البريد الإلكتروني للمكلّف",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "assignee_first_name",
    label: "Assignee First Name",
    label_ar: "الاسم الأول للمكلّف",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "assignee_last_name",
    label: "Assignee Last Name",
    label_ar: "اسم العائلة للمكلّف",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "assignee_username",
    label: "Assignee Username",
    label_ar: "اسم المستخدم للمكلّف",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "current_state_name",
    label: "Status",
    label_ar: "الحالة",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "states",
    multiselect: true,
  },
  {
    field: "current_state_state_type",
    label: "Current State State Type",
    label_ar: "نوع الحالة الحالية",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "classification_name",
    label: "Classification Name",
    label_ar: "اسم التصنيف",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
    multiselect: true,
  },
  {
    field: "department_name",
    label: "Department Name",
    label_ar: "اسم القسم",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "location_name",
    label: "Location Name",
    label_ar: "اسم الموقع",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
    multiselect: true,
  },
  // { field: "attachment_id", label: "Attachment Id", type: "string", category: "Core", sortable: false, filterable: false },
  {
    field: "workflow_name",
    label: "Workflow Name",
    label_ar: "اسم سير العمل",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "closed_by",
    label: "Closed By",
    label_ar: "أُغلق بواسطة",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "contractor",
    label: "Contractor",
    label_ar: "المقاول",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "contractor_user",
    label: "Contractor User",
    label_ar: "مستخدم المقاول",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "solved_by",
    label: "Solved By",
    label_ar: "تم الحل بواسطة",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "closed_date",
    label: "Closed Date",
    label_ar: "تاريخ الإغلاق",
    type: "date",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "rejected_by",
    label: "Rejected By",
    label_ar: "تم الرفض بواسطة",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "rejected_date",
    label: "Rejected Date",
    label_ar: "تاريخ الرفض",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "under_resolution_by",
    label: "Under Resolution By",
    label_ar: "قيد المعالجة بواسطة",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "approved_by",
    label: "Approved By",
    label_ar: "تمت الموافقة بواسطة",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "under_resolution_date",
    label: "Under Resolution Date",
    label_ar: "تاريخ قيد المعالجة",
    type: "date",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "approved_time",
    label: "Approved Time",
    label_ar: "وقت الموافقة",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "approved_at",
    label: "Approved At",
    label_ar: "تاريخ الموافقة",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "in_progress_by",
    label: "In Progress By",
    label_ar: "قيد التنفيذ بواسطة",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "in_progress_date",
    label: "In Progress Date",
    label_ar: "تاريخ بدء التنفيذ",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "ready_to_close_by",
    label: "Ready To Close By",
    label_ar: "جاهز للإغلاق بواسطة",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "ready_to_close_date",
    label: "Ready To Close Date",
    label_ar: "تاريخ الجاهزية للإغلاق",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reopened_by",
    label: "Reopened By",
    label_ar: "أعيد فتحه بواسطة",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "reopen_date",
    label: "Reopen Date",
    label_ar: "تاريخ إعادة الفتح",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "escalation_date",
    label: "Escalation Date",
    label_ar: "تاريخ التصعيد",
    type: "date",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "comments",
    label: "Comments",
    label_ar: "التعليقات",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
  },
  {
    field: "comments_array",
    label: "Comments Array",
    label_ar: "مصفوفة التعليقات",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
  },
  {
    field: "contractor_comment",
    label: "Contractor Comment",
    label_ar: "تعليق المقاول",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
  },
  {
    field: "before_attachments",
    label: "Before Attachments",
    label_ar: "المرفقات قبل التنفيذ",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
    isUrl: true,
  },
  {
    field: "before_attachment_array",
    label: "Before Attachment Array",
    label_ar: "مصفوفة المرفقات قبل التنفيذ",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
    isUrl: true,
  },
  {
    field: "after_attachments",
    label: "After Attachments",
    label_ar: "المرفقات بعد التنفيذ",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
    isUrl: true,
  },
  {
    field: "after_attachment_array",
    label: "After Attachment Array",
    label_ar: "مصفوفة المرفقات بعد التنفيذ",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
    isUrl: true,
  },
  {
    field: "attachments",
    label: "Attachments",
    label_ar: "المرفقات",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
    isUrl: true,
  },
  {
    field: "total_closing_duration",
    label: "Total Closing Duration",
    label_ar: "إجمالي مدة الإغلاق",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
  },
  {
    field: "task_id ",
    label: "Task ID",
    label_ar: "معرف المهمة",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
    isUrl: true,
  },
];

export const requestFields: ReportFieldDefinition[] = [
  // Core
  {
    field: "request_number",
    label: "Request Number",
    label_ar: "رقم الطلب",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "source",
    label: "Channel",
    label_ar: "القناة",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    multiselect: true,
    options: [
      { value: "web", label: "Web Portal" },
      { value: "mobile", label: "Mobile App" },
      { value: "email", label: "Email" },
      { value: "phone", label: "Phone" },
      { value: "walk_in", label: "Walk-in" },
      { value: "api", label: "API Integration" },
      { value: "social_media", label: "Social Media" },
      { value: "940_system", label: "940 System" },
      { value: "940_manual", label: "940 Manual" },
      { value: "field", label: "Field" },
      { value: "manual", label: "Manual Entry" },
      { value: "other", label: "Other" },
    ],
  },
  {
    field: "status_id",
    label: "Status",
    label_ar: "الحالة",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "requestStates",
    multiselect: true,
  },
  {
    field: "created_by_mobile",
    label: "Created By Mobile",
    label_ar: "هاتف المنشئ",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
  },

  {
    field: "reporter_name",
    label: "Reporter Name",
    label_ar: "اسم المبلّغ",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reporter_phone",
    label: "Reporter Phone",
    label_ar: "هاتف المبلّغ",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reporter_first_name",
    label: "Reporter First Name",
    label_ar: "الاسم الأول للمبلّغ",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reporter_last_name",
    label: "Reporter Last Name",
    label_ar: "اسم العائلة للمبلّغ",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "classification_name",
    label: "Classification Name",
    label_ar: "اسم التصنيف",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "location_name",
    label: "Location Name",
    label_ar: "اسم الموقع",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "locations",
  },
  {
    field: "location_id",
    label: "Location",
    label_ar: "الموقع",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "locations",
    multiselect: true,
  },
  {
    field: "title",
    label: "Title",
    label_ar: "العنوان",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "location_id",
    label: "Location",
    label_ar: "الموقع",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "locations",
    canBeColumn: false,
    multiselect: true,
  },
  {
    field: "classification_id",
    label: "Classification",
    label_ar: "التصنيف",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "classifications",
    canBeColumn: false,
    multiselect: true,
  },
  {
    field: "created_at",
    label: "Created At",
    label_ar: "تاريخ الإنشاء",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
];

// Action Logs Data Source Fields
export const actionLogFields: ReportFieldDefinition[] = [
  // Core
  {
    field: "id",
    label: "Log ID",
    label_ar: "معرف السجل",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "user_id",
    label: "User",
    label_ar: "المستخدم",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
  },
  {
    field: "action",
    label: "Action",
    label_ar: "الإجراء",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    defaultSelected: true,
    options: [
      { value: "create", label: "Create" },
      { value: "update", label: "Update" },
      { value: "delete", label: "Delete" },
      { value: "login", label: "Login" },
      { value: "logout", label: "Logout" },
      { value: "view", label: "View" },
    ],
  },
  {
    field: "module",
    label: "Module",
    label_ar: "الوحدة",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "description",
    label: "Description",
    label_ar: "الوصف",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: true,
    defaultSelected: true,
  },
  // { field: 'resource_id', label: 'Resource ID', type: 'string', category: 'Core', sortable: true, filterable: true },

  // Status
  {
    field: "status",
    label: "Status",
    label_ar: "الحالة",
    type: "enum",
    category: "Status",
    sortable: true,
    filterable: true,
    defaultSelected: true,
    options: [
      { value: "success", label: "Success" },
      { value: "failed", label: "Failed" },
    ],
  },
  {
    field: "error_msg",
    label: "Error Message",
    label_ar: "رسالة الخطأ",
    type: "string",
    category: "Status",
    sortable: false,
    filterable: true,
  },
  {
    field: "duration",
    label: "Duration (ms)",
    label_ar: "المدة (مللي ثانية)",
    type: "number",
    category: "Status",
    sortable: true,
    filterable: true,
  },

  // User
  {
    field: "user_username",
    label: "Username",
    label_ar: "اسم المستخدم",
    type: "string",
    category: "User",
    sortable: true,
    filterable: true,
    defaultSelected: true,
    relationField: "user",
  },
  {
    field: "user_email",
    label: "User Email",
    label_ar: "البريد الإلكتروني للمستخدم",
    type: "string",
    category: "User",
    sortable: true,
    filterable: true,
    relationField: "user",
  },
  {
    field: "user_first_name",
    label: "User First Name",
    label_ar: "الاسم الأول للمستخدم",
    type: "string",
    category: "User",
    sortable: true,
    filterable: true,
    relationField: "user",
  },
  {
    field: "user_last_name",
    label: "User Last Name",
    label_ar: "اسم العائلة للمستخدم",
    type: "string",
    category: "User",
    sortable: true,
    filterable: true,
    relationField: "user",
  },

  // Timestamps
  {
    field: "created_at",
    label: "Timestamp",
    label_ar: "الطابع الزمني",
    type: "datetime",
    category: "Timestamps",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
];

// Users Data Source Fields
export const userFields: ReportFieldDefinition[] = [
  // Identity
  {
    field: "id",
    label: "User ID",
    label_ar: "معرف المستخدم",
    type: "enum",
    category: "Identity",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
  },
  {
    field: "username",
    label: "Username",
    label_ar: "اسم المستخدم",
    type: "string",
    category: "Identity",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "email",
    label: "Email",
    label_ar: "البريد الإلكتروني",
    type: "string",
    category: "Identity",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "first_name",
    label: "First Name",
    label_ar: "الاسم الأول",
    type: "string",
    category: "Identity",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "last_name",
    label: "Last Name",
    label_ar: "اسم العائلة",
    type: "string",
    category: "Identity",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "phone",
    label: "Phone",
    label_ar: "الهاتف",
    type: "string",
    category: "Identity",
    sortable: true,
    filterable: true,
  },

  // Status
  {
    field: "is_active",
    label: "Active",
    label_ar: "نشط",
    type: "boolean",
    category: "Status",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "is_super_admin",
    label: "Super Admin",
    label_ar: "مدير عام",
    type: "boolean",
    category: "Status",
    sortable: true,
    filterable: true,
  },
  {
    field: "last_login_at",
    label: "Last Login",
    label_ar: "آخر تسجيل دخول",
    type: "datetime",
    category: "Status",
    sortable: true,
    filterable: true,
  },

  // Relations
  {
    field: "department_name",
    label: "Primary Department",
    label_ar: "القسم الرئيسي",
    type: "enum",
    category: "Relations",
    sortable: true,
    filterable: true,
    relationField: "department",
    dynamicOptions: "departments",
  },
  {
    field: "location_name",
    label: "Primary Location",
    label_ar: "الموقع الرئيسي",
    type: "enum",
    category: "Relations",
    sortable: true,
    filterable: true,
    relationField: "location",
    dynamicOptions: "locations",
  },

  // Timestamps
  {
    field: "created_at",
    label: "Created At",
    label_ar: "تاريخ الإنشاء",
    type: "datetime",
    category: "Timestamps",
    sortable: true,
    filterable: true,
  },
];

export const userPerformanceFields: ReportFieldDefinition[] = [
  {
    field: "performed_by_id",
    label: "Performer",
    label_ar: "المنفذ",
    type: "enum",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    canBeColumn: false,
  },
  {
    field: "incident_id",
    label: "Incident ID",
    label_ar: "معرف الحادث",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    canBeColumn: true,
  },
  {
    field: "incident_number",
    label: "Incident Number",
    label_ar: "رقم الحادث",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    defaultSelected: false,
    canBeColumn: true,
  },
  {
    field: "record_type",
    label: "Record Type",
    label_ar: "نوع السجل",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    defaultSelected: false,
    canBeColumn: true,
  },
  {
    field: "created_at",
    label: "Created At",
    label_ar: "تاريخ الإنشاء",
    type: "datetime",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    canBeColumn: false,
  },
  // columsn and non filterable

  {
    field: "timestamp",
    label: "Timestamp",
    label_ar: "الطابع الزمني",
    type: "datetime",
    category: "Basic Info",
    sortable: false,
    filterable: false,
    canBeColumn: true,
    defaultSelected: true,
  },
  {
    field: "user",
    label: "User",
    label_ar: "المستخدم",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    canBeColumn: true,
    defaultSelected: true,
  },
  {
    field: "resource_id",
    label: "Resource ID",
    label_ar: "معرف المورد",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    canBeColumn: false,
  },
  {
    field: "classification",
    label: "Classification name",
    label_ar: "اسم التصنيف",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: false,
    canBeColumn: true,
    defaultSelected: true,
  },
  {
    field: "status",
    label: "Status",
    label_ar: "الحالة",
    type: "enum",
    dynamicOptions: "states",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    multiselect: true,
    canBeColumn: true,
    defaultSelected: true,
  },
  {
    field: "comments",
    label: "Comments",
    label_ar: "التعليقات",
    type: "string",
    category: "Basic Info",
    sortable: false,
    filterable: false,
    canBeColumn: true,
    defaultSelected: true,
  },
  {
    field: "attachments",
    label: "Attachments",
    label_ar: "المرفقات",
    type: "string",
    category: "Basic Info",
    sortable: false,
    filterable: false,
    canBeColumn: true,
    defaultSelected: true,
    isUrl: true,
  },
  {
    field: "location_name",
    label: "Location Name",
    label_ar: "اسم الموقع",
    type: "enum",
    filterable: true,
    dynamicOptions: "locations",
    sortable: true,
    category: "Basic Info",
    defaultSelected: true,
    multiselect: true,
  },
  {
    field: "location_id",
    label: "Location",
    label_ar: "الموقع",
    type: "enum",
    filterable: true,
    dynamicOptions: "locations",
    sortable: true,
    category: "Basic Info",
    canBeColumn: false,
    multiselect: true,
  },
  {
    field: "transitioned_at",
    label: "Transitioned At",
    label_ar: "تاريخ الانتقال",
    type: "datetime",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    canBeColumn: true,
  },
  {
    field: "classification_id",
    label: "Classification",
    label_ar: "التصنيف",
    type: "enum",
    filterable: true,
    dynamicOptions: "classifications",
    sortable: true,
    category: "Basic Info",
    canBeColumn: true,
    multiselect: true,
  },
];

// Departments Data Source Fields
export const departmentFields: ReportFieldDefinition[] = [
  // Basic Info
  {
    field: "id",
    label: "Department ID",
    label_ar: "معرف القسم",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
  },
  {
    field: "name",
    label: "Name",
    label_ar: "الاسم",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "code",
    label: "Code",
    label_ar: "الرمز",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "description",
    label: "Description",
    label_ar: "الوصف",
    type: "string",
    category: "Basic Info",
    sortable: false,
    filterable: true,
  },

  // Hierarchy
  {
    field: "level",
    label: "Level",
    label_ar: "المستوى",
    type: "number",
    category: "Hierarchy",
    sortable: true,
    filterable: true,
  },
  {
    field: "path",
    label: "Path",
    label_ar: "المسار",
    type: "string",
    category: "Hierarchy",
    sortable: true,
    filterable: true,
  },
  {
    field: "parent_id",
    label: "Parent Department",
    label_ar: "القسم الأب",
    type: "enum",
    category: "Hierarchy",
    sortable: true,
    filterable: true,
    relationField: "parent",
    dynamicOptions: "departments",
  },

  // Relations
  {
    field: "manager_username",
    label: "Manager Username",
    label_ar: "اسم مستخدم المدير",
    type: "string",
    category: "Relations",
    sortable: true,
    filterable: true,
    relationField: "manager",
  },
  {
    field: "manager_first_name",
    label: "Manager First Name",
    label_ar: "الاسم الأول للمدير",
    type: "string",
    category: "Relations",
    sortable: true,
    filterable: true,
    relationField: "manager",
  },
  {
    field: "manager_last_name",
    label: "Manager Last Name",
    label_ar: "اسم العائلة للمدير",
    type: "string",
    category: "Relations",
    sortable: true,
    filterable: true,
    relationField: "manager",
  },

  // Status
  {
    field: "is_active",
    label: "Active",
    label_ar: "نشط",
    type: "boolean",
    category: "Status",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "sort_order",
    label: "Sort Order",
    label_ar: "ترتيب الفرز",
    type: "number",
    category: "Status",
    sortable: true,
    filterable: true,
  },

  // Timestamps
  {
    field: "created_at",
    label: "Created At",
    label_ar: "تاريخ الإنشاء",
    type: "datetime",
    category: "Timestamps",
    sortable: true,
    filterable: true,
  },
];

// Locations Data Source Fields
export const locationFields: ReportFieldDefinition[] = [
  {
    field: "location_name",
    label: "Location Name",
    label_ar: "اسم الموقع",
    type: "enum",
    filterable: false,
    dynamicOptions: "locations",
    sortable: true,
    category: "Basic Info",
    defaultSelected: true,
  },
  {
    field: "channel",
    label: "Channel",
    label_ar: "القناة",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    multiselect: true,
    options: [
      { value: "web", label: "Web Portal" },
      { value: "mobile", label: "Mobile App" },
      { value: "email", label: "Email" },
      { value: "phone", label: "Phone" },
      { value: "walk_in", label: "Walk-in" },
      { value: "api", label: "API Integration" },
      { value: "social_media", label: "Social Media" },
      { value: "940_system", label: "940 System" },
      { value: "940_manual", label: "940 Manual" },
      { value: "field", label: "Field" },
      { value: "manual", label: "Manual Entry" },
      { value: "other", label: "Other" },
    ],
  },
  {
    field: "parent_location_name",
    label: "Parent Location",
    label_ar: "الموقع الأب",
    type: "enum",
    filterable: false,
    dynamicOptions: "locations",
    sortable: true,
    category: "Basic Info",
    defaultSelected: true,
  },
  {
    field: "status_name",
    label: "Status",
    label_ar: "الحالة",
    type: "enum",
    dynamicOptions: "states",
    filterable: true,
    sortable: true,
    category: "Basic Info",
    defaultSelected: true,
    multiselect: true,
  },
  {
    field: "incident_count",
    label: "No. of Incidents",
    label_ar: "عدد الحوادث",
    type: "number",
    filterable: false,
    sortable: true,
    category: "Basic Info",
    defaultSelected: true,
  },
  {
    field: "location_id",
    label: "Location",
    label_ar: "الموقع",
    type: "enum",
    filterable: true,
    dynamicOptions: "locations",
    sortable: true,
    category: "Basic Info",
    canBeColumn: false,
    multiselect: true,
  },
  {
    field: "classification_id",
    label: "Classification",
    label_ar: "التصنيف",
    type: "enum",
    filterable: true,
    dynamicOptions: "classifications",
    sortable: true,
    category: "Basic Info",
    canBeColumn: false,
    multiselect: true,
  },
  {
    field: "classification_name",
    label: "Classification Name",
    label_ar: "اسم التصنيف",
    type: "enum",
    filterable: false,
    dynamicOptions: "classifications",
    sortable: true,
    category: "Basic Info",
  },
  {
    field: "percentage",
    label: "Percentage",
    label_ar: "النسبة المئوية",
    type: "string",
    filterable: false,
    sortable: false,
    category: "Basic Info",
  },
];

export const locationCountBasedFields: ReportFieldDefinition[] = [
  // Basic Info
  {
    field: "location_name",
    label: "Location",
    label_ar: "الموقع",
    type: "enum",
    filterable: false,
    dynamicOptions: "locations",
    sortable: true,
    defaultSelected: true,
    category: "Basic Info",
  },
  {
    field: "parent_location_name",
    label: "Parent Location",
    label_ar: "الموقع الأب",
    type: "string",
    filterable: false,
    sortable: true,
    defaultSelected: true,
    category: "Basic Info",
  },
  {
    field: "incident_count",
    label: "No. of Incidents",
    label_ar: "عدد الحوادث",
    type: "number",
    filterable: false,
    sortable: true,
    defaultSelected: true,
    category: "Basic Info",
  },
  {
    field: "location_id",
    label: "Location",
    label_ar: "الموقع",
    type: "enum",
    filterable: true,
    dynamicOptions: "locations",
    sortable: true,
    category: "Basic Info",
    canBeColumn: false,
    multiselect: true,
  },
  {
    field: "classification_id",
    label: "Classification",
    label_ar: "التصنيف",
    type: "enum",
    filterable: true,
    dynamicOptions: "classifications",
    sortable: true,
    category: "Basic Info",
    canBeColumn: false,
    multiselect: true,
  },
  {
    field: "classification_name",
    label: "Classification Name",
    label_ar: "اسم التصنيف",
    type: "enum",
    filterable: false,
    dynamicOptions: "classifications",
    sortable: true,
    category: "Basic Info",
  },
];

export const classificationFields: ReportFieldDefinition[] = [
  {
    field: "classification_name",
    label: "Classification",
    label_ar: "التصنيف",
    type: "enum",
    filterable: false,
    dynamicOptions: "classifications",
    sortable: true,
    category: "Basic Info",
    defaultSelected: true,
  },
  {
    field: "parent_classification_name",
    label: "Parent Classification",
    label_ar: "التصنيف الأب",
    type: "enum",
    filterable: false,
    dynamicOptions: "classifications",
    sortable: true,
    category: "Basic Info",
    defaultSelected: true,
  },
  {
    field: "channel",
    label: "Channel",
    label_ar: "القناة",
    type: "enum",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    multiselect: true,
    options: [
      { value: "web", label: "Web Portal" },
      { value: "mobile", label: "Mobile App" },
      { value: "email", label: "Email" },
      { value: "phone", label: "Phone" },
      { value: "walk_in", label: "Walk-in" },
      { value: "api", label: "API Integration" },
      { value: "social_media", label: "Social Media" },
      { value: "940_system", label: "940 System" },
      { value: "940_manual", label: "940 Manual" },
      { value: "field", label: "Field" },
      { value: "manual", label: "Manual Entry" },
      { value: "other", label: "Other" },
    ],
  },
  {
    field: "status_name",
    label: "Status",
    label_ar: "الحالة",
    type: "enum",
    dynamicOptions: "states",
    filterable: true,
    sortable: true,
    category: "Basic Info",
    defaultSelected: true,
    multiselect: true,
  },
  {
    field: "incident_count",
    label: "No. of Incidents",
    label_ar: "عدد الحوادث",
    type: "number",
    filterable: false,
    sortable: true,
    category: "Basic Info",
    defaultSelected: true,
  },
  {
    field: "classification_id",
    label: "Classification",
    label_ar: "التصنيف",
    type: "enum",
    filterable: true,
    dynamicOptions: "classifications",
    sortable: true,
    category: "Basic Info",
    canBeColumn: false,
    multiselect: true,
  },
  {
    field: "location_name",
    label: "Location Name",
    label_ar: "اسم الموقع",
    type: "enum",
    filterable: false,
    dynamicOptions: "locations",
    sortable: true,
    category: "Basic Info",
  },
  {
    field: "location_id",
    label: "Location",
    label_ar: "الموقع",
    type: "enum",
    filterable: true,
    dynamicOptions: "locations",
    sortable: true,
    category: "Basic Info",
    canBeColumn: false,
    multiselect: true,
  },
  {
    field: "percentage",
    label: "Percentage",
    label_ar: "النسبة المئوية",
    type: "string",
    filterable: false,
    sortable: false,
    category: "Basic Info",
  },
];

export const classificationCountBasedFields: ReportFieldDefinition[] = [
  // Basic Info
  {
    field: "classification_name",
    label: "Classification",
    label_ar: "التصنيف",
    type: "enum",
    filterable: false,
    dynamicOptions: "classifications",
    sortable: true,
    defaultSelected: true,
    category: "Basic Info",
  },
  {
    field: "parent_classification_name",
    label: "Parent Classification",
    label_ar: "التصنيف الأب",
    type: "string",
    filterable: false,
    sortable: true,
    defaultSelected: true,
    category: "Basic Info",
  },
  {
    field: "incident_count",
    label: "No. of Incidents",
    label_ar: "عدد الحوادث",
    type: "number",
    filterable: false,
    sortable: true,
    defaultSelected: true,
    category: "Basic Info",
  },
  {
    field: "classification_id",
    label: "Classification",
    label_ar: "التصنيف",
    type: "enum",
    filterable: true,
    dynamicOptions: "classifications",
    sortable: true,
    category: "Basic Info",
    canBeColumn: false,
  },
  {
    field: "location_id",
    label: "Location",
    label_ar: "الموقع",
    type: "enum",
    filterable: true,
    dynamicOptions: "locations",
    sortable: true,
    category: "Basic Info",
    canBeColumn: false,
    multiselect: true,
  },
  {
    field: "location_name",
    label: "Location Name",
    label_ar: "اسم الموقع",
    type: "enum",
    filterable: false,
    dynamicOptions: "locations",
    sortable: true,
    category: "Basic Info",
  },
];

// Workflows Data Source Fields
export const workflowFields: ReportFieldDefinition[] = [
  // Basic Info
  {
    field: "id",
    label: "Workflow ID",
    label_ar: "معرف سير العمل",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
  },
  {
    field: "name",
    label: "Name",
    label_ar: "الاسم",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "code",
    label: "Code",
    label_ar: "الرمز",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "description",
    label: "Description",
    label_ar: "الوصف",
    type: "string",
    category: "Basic Info",
    sortable: false,
    filterable: true,
  },
  {
    field: "version",
    label: "Version",
    label_ar: "الإصدار",
    type: "number",
    category: "Basic Info",
    sortable: true,
    filterable: true,
  },

  // Status
  {
    field: "is_active",
    label: "Active",
    label_ar: "نشط",
    type: "boolean",
    category: "Status",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "is_default",
    label: "Default Workflow",
    label_ar: "سير العمل الافتراضي",
    type: "boolean",
    category: "Status",
    sortable: true,
    filterable: true,
  },

  // Counts
  {
    field: "states_count",
    label: "States Count",
    label_ar: "عدد الحالات",
    type: "number",
    category: "Counts",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "transitions_count",
    label: "Transitions Count",
    label_ar: "عدد الانتقالات",
    type: "number",
    category: "Counts",
    sortable: true,
    filterable: true,
  },

  // Matching Config
  {
    field: "priority_min",
    label: "Min Priority",
    label_ar: "أدنى أولوية",
    type: "number",
    category: "Matching",
    sortable: true,
    filterable: true,
  },
  {
    field: "priority_max",
    label: "Max Priority",
    label_ar: "أعلى أولوية",
    type: "number",
    category: "Matching",
    sortable: true,
    filterable: true,
  },

  // Creator
  {
    field: "created_by_username",
    label: "Created By",
    label_ar: "أُنشئ بواسطة",
    type: "string",
    category: "Creator",
    sortable: true,
    filterable: true,
    relationField: "created_by",
    dynamicOptions: "users",
  },

  // Timestamps
  {
    field: "created_at",
    label: "Created At",
    label_ar: "تاريخ الإنشاء",
    type: "datetime",
    category: "Timestamps",
    sortable: true,
    filterable: true,
  },
  {
    field: "updated_at",
    label: "Updated At",
    label_ar: "تاريخ التحديث",
    type: "datetime",
    category: "Timestamps",
    sortable: true,
    filterable: true,
  },
];

// All Data Sources with their definitions
export const DATA_SOURCES: DataSourceDefinition[] = [
  {
    key: "incidents",
    label: "Incidents",
    description: "Incident tracking and management data",
    icon: "AlertCircle",
    fields: incidentFields,
  },
  {
    key: "requests",
    label: "Requests",
    description: "Request tracking and management data",
    icon: "FileText",
    fields: requestFields,
  },
  {
    key: "action_logs",
    label: "Action Logs",
    description: "System audit trail and user activity",
    icon: "FileText",
    fields: actionLogFields,
  },
  {
    key: "users",
    label: "Users",
    description: "User accounts and profiles",
    icon: "Users",
    fields: userFields,
  },
  {
    key: "users_performance",
    label: "User performance",
    description: "User performance data",
    icon: "Users",
    fields: userPerformanceFields,
  },
  {
    key: "departments",
    label: "Departments",
    description: "Organizational department structure",
    icon: "Building2",
    fields: departmentFields,
  },
  {
    key: "locations_by_status",
    label: "Locations",
    description: "Physical location hierarchy",
    icon: "MapPin",
    fields: locationFields,
  },
  {
    key: "locations_by_count",
    label: "Location Count Based",
    description: "Location-wise record counts",
    icon: "BarChart3",
    fields: locationCountBasedFields,
  },
  {
    key: "classifications_by_status",
    label: "Classifications",
    description: "Classification hierarchy",
    icon: "Tag",
    fields: classificationFields,
  },
  {
    key: "classifications_by_count",
    label: "Classification Count Based",
    description: "Classification-wise record counts",
    icon: "BarChart3",
    fields: classificationCountBasedFields,
  },
  {
    key: "workflows",
    label: "Workflows",
    description: "Workflow definitions and configurations",
    icon: "GitBranch",
    fields: workflowFields,
  },
];

// Helper function to get fields for a data source
export const getFieldsForDataSource = (
  dataSource: string,
): ReportFieldDefinition[] => {
  const source = DATA_SOURCES.find((ds) => ds.key === dataSource);
  return source?.fields || [];
};

// Helper function to get default selected fields for a data source
export const getDefaultFieldsForDataSource = (
  dataSource: string,
): { field: string; label: string; label_ar: string }[] => {
  const fields = getFieldsForDataSource(dataSource);
  return fields
    .filter((f) => f.defaultSelected)
    .map((f) => ({ field: f.field, label: f.label, label_ar: f.label_ar }));
};

// Helper function to get operators for a field type
export const getOperatorsForFieldType = (
  fieldType: string,
): { value: FilterOperator; label: string }[] => {
  return FILTER_OPERATORS_BY_TYPE[fieldType] || FILTER_OPERATORS_BY_TYPE.string;
};

// Helper function to group fields by category
export const groupFieldsByCategory = (
  fields: ReportFieldDefinition[],
): Record<string, ReportFieldDefinition[]> => {
  return fields
    .filter((f) => f?.canBeColumn === true || f.canBeColumn === undefined)
    .reduce(
      (acc, field) => {
        const category = field.category || "Other";
        if (!acc[category]) {
          acc[category] = [];
        }
        acc[category].push(field);
        return acc;
      },
      {} as Record<string, ReportFieldDefinition[]>,
    );
};
