import type {
  DataSourceDefinition,
  ReportFieldDefinition,
  FilterOperator,
} from "../types";

// Filter operators by field type
export const FILTER_OPERATORS_BY_TYPE: Record<
  string,
  { value: FilterOperator; label: string }[]
> = {
  string: [
    { value: "equals", label: "Equals" },
    { value: "not_equals", label: "Does not equal" },
    { value: "contains", label: "Contains" },
    { value: "not_contains", label: "Does not contain" },
    { value: "starts_with", label: "Starts with" },
    { value: "ends_with", label: "Ends with" },
    { value: "is_empty", label: "Is empty" },
    { value: "is_not_empty", label: "Is not empty" },
  ],
  number: [
    { value: "equals", label: "Equals" },
    { value: "not_equals", label: "Does not equal" },
    { value: "greater_than", label: "Greater than" },
    { value: "less_than", label: "Less than" },
    { value: "greater_than_or_equal", label: "Greater than or equal" },
    { value: "less_than_or_equal", label: "Less than or equal" },
    { value: "between", label: "Between" },
    { value: "is_empty", label: "Is empty" },
    { value: "is_not_empty", label: "Is not empty" },
  ],
  date: [
    { value: "on_date", label: "On date" },
    { value: "before", label: "Before" },
    { value: "after", label: "After" },
    { value: "between", label: "Between" },
    { value: "is_empty", label: "Is empty" },
    { value: "is_not_empty", label: "Is not empty" },
  ],
  datetime: [
    { value: "on_date", label: "On date" },
    { value: "before", label: "Before" },
    { value: "after", label: "After" },
    { value: "between", label: "Between" },
    { value: "is_empty", label: "Is empty" },
    { value: "is_not_empty", label: "Is not empty" },
  ],
  boolean: [{ value: "equals", label: "Is" }],
  enum: [
    { value: "equals", label: "Equals" },
    { value: "not_equals", label: "Does not equal" },
    { value: "in", label: "Is any of" },
    { value: "not_in", label: "Is none of" },
  ],
  relation: [
    { value: "equals", label: "Equals" },
    { value: "not_equals", label: "Does not equal" },
    { value: "contains", label: "Contains" },
    { value: "is_empty", label: "Is empty" },
    { value: "is_not_empty", label: "Is not empty" },
  ],
};

// Incidents Data Source Fields
export const incidentFields: ReportFieldDefinition[] = [
  {
    field: "id",
    label: "id",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "incident_number",
    label: "Incident Number",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "title",
    label: "Title",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "description",
    label: "Description",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "priority",
    label: "Priority",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    options: [
      { value: 1, label: "Critical" },
      { value: 2, label: "High" },
      { value: 3, label: "Medium" },
      { value: 4, label: "Low" },
      { value: 5, label: "Minimal" },
    ],
  },
  {
    field: "severity",
    label: "Severity",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    options: [
      { value: 1, label: "Critical" },
      { value: 2, label: "High" },
      { value: 3, label: "Medium" },
      { value: 4, label: "Low" },
      { value: 5, label: "Minimal" },
    ],
  },
  {
    field: "assignee_id",
    label: "Assignee",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
  },
  {
    field: "classification_id",
    label: "Classification",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "classifications",
    canBeColumn: false,
  },
  {
    field: "department_id",
    label: "Department",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "departments",
    canBeColumn: false,
  },
  {
    field: "location_id",
    label: "Location",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "locations",
    canBeColumn: false,
  },
  {
    field: "latitude",
    label: "Latitude",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
  },
  {
    field: "longitude",
    label: "Longitude",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
  },
  {
    field: "due_date",
    label: "Due Date",
    type: "date",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "resolved_at",
    label: "Resolved At",
    type: "date",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "closed_at",
    label: "Closed At",
    type: "date",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "sla_breached",
    label: "Sla Breached",
    type: "boolean",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "sla_deadline",
    label: "Sla Deadline",
    type: "date",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reporter_phone",
    label: "Reporter Phone",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reporter_id",
    label: "Reporter",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
  },
  {
    field: "reporter_email",
    label: "Reporter Email",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reporter_name",
    label: "Reporter Name",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  // { field: "custom_fields", label: "Custom Fields", type: "string", category: "Core", sortable: true, filterable: true },
  {
    field: "created_at",
    label: "Created At",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "updated_at",
    label: "Updated At",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "deleted_at",
    label: "Deleted At",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "record_type",
    label: "Record Type",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "source_incident_id",
    label: "Source Incident Id",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "converted_request_id",
    label: "Converted Request Id",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "channel",
    label: "Channel",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    options: [
      { value: "web", label: "Web Portal" },
      { value: "mobile", label: "Mobile App" },
      { value: "email", label: "Email" },
      { value: "phone", label: "Phone" },
      { value: "walk_in", label: "Walk-in" },
      { value: "api", label: "API Integration" },
      { value: "social_media", label: "Social Media" },
      { value: "940_system", label: "940 System" },
      { value: "940_manual", label: "940 Manual" },
      { value: "field", label: "Field" },
      { value: "manual", label: "Manual Entry" },
      { value: "other", label: "Other" },
    ],
  },
  {
    field: "created_by_id",
    label: "Created By",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
  },
  {
    field: "created_by_name",
    label: "Created By Name",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "name",
  },
  {
    field: "created_by_mobile",
    label: "Created By Mobile",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "mobile",
  },
  {
    field: "evaluation_count",
    label: "Evaluation Count",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "address",
    label: "Address",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "city",
    label: "City",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "state",
    label: "State",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "country",
    label: "Country",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "postal_code",
    label: "Postal Code",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "source",
    label: "Source",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    options: [
      { value: "web", label: "Web Portal" },
      { value: "mobile", label: "Mobile App" },
      { value: "email", label: "Email" },
      { value: "phone", label: "Phone" },
      { value: "walk_in", label: "Walk-in" },
      { value: "api", label: "API Integration" },
      { value: "social_media", label: "Social Media" },
      { value: "940_system", label: "940 System" },
      { value: "940_manual", label: "940 Manual" },
      { value: "field", label: "Field" },
      { value: "manual", label: "Manual Entry" },
      { value: "other", label: "Other" },
    ],
  },
  {
    field: "version",
    label: "Version",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "master_incident_id",
    label: "Master Incident Id",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "is_merged",
    label: "Is Merged",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "merged_at",
    label: "Merged At",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "merged_by_user_id",
    label: "Merged By User",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "source_incident_ids",
    label: "Source Incident Ids",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "ready_to_close_expires_at",
    label: "Ready To Close Expires At",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "ready_to_close_duration",
    label: "Ready To Close Duration",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "ready_to_close_notified",
    label: "Ready To Close Notified",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reporter_first_name",
    label: "Reporter First Name",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reporter_last_name",
    label: "Reporter Last Name",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reporter_username",
    label: "Reporter Username",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "assignee_email",
    label: "Assignee Email",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "assignee_first_name",
    label: "Assignee First Name",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "assignee_last_name",
    label: "Assignee Last Name",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "assignee_username",
    label: "Assignee Username",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "current_state_name",
    label: "Current State Name",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "current_state_state_type",
    label: "Current State State Type",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "classification_name",
    label: "Classification Name",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "department_name",
    label: "Department Name",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "location_name",
    label: "Location Name",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  // { field: "attachment_id", label: "Attachment Id", type: "string", category: "Core", sortable: false, filterable: false },
  {
    field: "workflow_name",
    label: "Workflow Name",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "closed_by",
    label: "Closed By",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "contractor",
    label: "Contractor",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "contractor_user",
    label: "Contractor User",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "solved_by",
    label: "Solved By",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "closed_date",
    label: "Closed Date",
    type: "date",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "rejected_by",
    label: "Rejected By",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "rejected_date",
    label: "Rejected Date",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "under_resolution_by",
    label: "Under Resolution By",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "approved_by",
    label: "Approved By",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "under_resolution_date",
    label: "Under Resolution Date",
    type: "date",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "approved_time",
    label: "Approved Time",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "approved_at",
    label: "Approved At",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "in_progress_by",
    label: "In Progress By",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "in_progress_date",
    label: "In Progress Date",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "ready_to_close_by",
    label: "Ready To Close By",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "ready_to_close_date",
    label: "Ready To Close Date",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reopened_by",
    label: "Reopened By",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
    relationField: "userId",
  },
  {
    field: "reopen_date",
    label: "Reopen Date",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "escalation_date",
    label: "Escalation Date",
    type: "date",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "comments",
    label: "Comments",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
  },
  {
    field: "comments_array",
    label: "Comments Array",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
  },
  {
    field: "contractor_comment",
    label: "Contractor Comment",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
  },
  {
    field: "before_attachments",
    label: "Before Attachments",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
  },
  {
    field: "before_attachment_array",
    label: "Before Attachment Array",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
  },
  {
    field: "after_attachments",
    label: "After Attachments",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
  },
  {
    field: "after_attachment_array",
    label: "After Attachment Array",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
  },
  {
    field: "attachments",
    label: "Attachments",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: false,
  },
];

export const requestFields: ReportFieldDefinition[] = [
  // Core
  {
    field: "request_number",
    label: "Request Number",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "created_by_mobile",
    label: "Created By Mobile",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
  },

  {
    field: "reporter_name",
    label: "Reporter Name",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reporter_phone",
    label: "Reporter Phone",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reporter_first_name",
    label: "Reporter First Name",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "reporter_last_name",
    label: "Reporter Last Name",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "classification_name",
    label: "Classification Name",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "location_name",
    label: "Location Name",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    dynamicOptions: "locations",
  },
  {
    field: "title",
    label: "Title",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "created_at",
    label: "Created At",
    type: "datetime",
    category: "Core",
    sortable: true,
    filterable: true,
  },
];

// Action Logs Data Source Fields
export const actionLogFields: ReportFieldDefinition[] = [
  // Core
  {
    field: "id",
    label: "Log ID",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
  },
  {
    field: "action",
    label: "Action",
    type: "enum",
    category: "Core",
    sortable: true,
    filterable: true,
    defaultSelected: true,
    options: [
      { value: "create", label: "Create" },
      { value: "update", label: "Update" },
      { value: "delete", label: "Delete" },
      { value: "login", label: "Login" },
      { value: "logout", label: "Logout" },
      { value: "view", label: "View" },
    ],
  },
  {
    field: "module",
    label: "Module",
    type: "string",
    category: "Core",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "description",
    label: "Description",
    type: "string",
    category: "Core",
    sortable: false,
    filterable: true,
    defaultSelected: true,
  },
  // { field: 'resource_id', label: 'Resource ID', type: 'string', category: 'Core', sortable: true, filterable: true },

  // Status
  {
    field: "status",
    label: "Status",
    type: "enum",
    category: "Status",
    sortable: true,
    filterable: true,
    defaultSelected: true,
    options: [
      { value: "success", label: "Success" },
      { value: "failed", label: "Failed" },
    ],
  },
  {
    field: "error_msg",
    label: "Error Message",
    type: "string",
    category: "Status",
    sortable: false,
    filterable: true,
  },
  {
    field: "duration",
    label: "Duration (ms)",
    type: "number",
    category: "Status",
    sortable: true,
    filterable: true,
  },

  // User
  {
    field: "user_username",
    label: "Username",
    type: "string",
    category: "User",
    sortable: true,
    filterable: true,
    defaultSelected: true,
    relationField: "user",
  },
  {
    field: "user_email",
    label: "User Email",
    type: "string",
    category: "User",
    sortable: true,
    filterable: true,
    relationField: "user",
  },
  {
    field: "user_first_name",
    label: "User First Name",
    type: "string",
    category: "User",
    sortable: true,
    filterable: true,
    relationField: "user",
  },
  {
    field: "user_last_name",
    label: "User Last Name",
    type: "string",
    category: "User",
    sortable: true,
    filterable: true,
    relationField: "user",
  },

  // Timestamps
  {
    field: "created_at",
    label: "Timestamp",
    type: "datetime",
    category: "Timestamps",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
];

// Users Data Source Fields
export const userFields: ReportFieldDefinition[] = [
  // Identity
  {
    field: "id",
    label: "User ID",
    type: "enum",
    category: "Identity",
    sortable: true,
    filterable: true,
    dynamicOptions: "users",
  },
  {
    field: "username",
    label: "Username",
    type: "string",
    category: "Identity",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "email",
    label: "Email",
    type: "string",
    category: "Identity",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "first_name",
    label: "First Name",
    type: "string",
    category: "Identity",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "last_name",
    label: "Last Name",
    type: "string",
    category: "Identity",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "phone",
    label: "Phone",
    type: "string",
    category: "Identity",
    sortable: true,
    filterable: true,
  },

  // Status
  {
    field: "is_active",
    label: "Active",
    type: "boolean",
    category: "Status",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "is_super_admin",
    label: "Super Admin",
    type: "boolean",
    category: "Status",
    sortable: true,
    filterable: true,
  },
  {
    field: "last_login_at",
    label: "Last Login",
    type: "datetime",
    category: "Status",
    sortable: true,
    filterable: true,
  },

  // Relations
  {
    field: "department_name",
    label: "Primary Department",
    type: "enum",
    category: "Relations",
    sortable: true,
    filterable: true,
    relationField: "department",
    dynamicOptions: "departments",
  },
  {
    field: "location_name",
    label: "Primary Location",
    type: "enum",
    category: "Relations",
    sortable: true,
    filterable: true,
    relationField: "location",
    dynamicOptions: "locations",
  },

  // Timestamps
  {
    field: "created_at",
    label: "Created At",
    type: "datetime",
    category: "Timestamps",
    sortable: true,
    filterable: true,
  },
];

// Departments Data Source Fields
export const departmentFields: ReportFieldDefinition[] = [
  // Basic Info
  {
    field: "id",
    label: "Department ID",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
  },
  {
    field: "name",
    label: "Name",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "code",
    label: "Code",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "description",
    label: "Description",
    type: "string",
    category: "Basic Info",
    sortable: false,
    filterable: true,
  },

  // Hierarchy
  {
    field: "level",
    label: "Level",
    type: "number",
    category: "Hierarchy",
    sortable: true,
    filterable: true,
  },
  {
    field: "path",
    label: "Path",
    type: "string",
    category: "Hierarchy",
    sortable: true,
    filterable: true,
  },
  {
    field: "parent_id",
    label: "Parent Department",
    type: "enum",
    category: "Hierarchy",
    sortable: true,
    filterable: true,
    relationField: "parent",
    dynamicOptions: "departments",
  },

  // Relations
  {
    field: "manager_username",
    label: "Manager Username",
    type: "string",
    category: "Relations",
    sortable: true,
    filterable: true,
    relationField: "manager",
  },
  {
    field: "manager_first_name",
    label: "Manager First Name",
    type: "string",
    category: "Relations",
    sortable: true,
    filterable: true,
    relationField: "manager",
  },
  {
    field: "manager_last_name",
    label: "Manager Last Name",
    type: "string",
    category: "Relations",
    sortable: true,
    filterable: true,
    relationField: "manager",
  },

  // Status
  {
    field: "is_active",
    label: "Active",
    type: "boolean",
    category: "Status",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "sort_order",
    label: "Sort Order",
    type: "number",
    category: "Status",
    sortable: true,
    filterable: true,
  },

  // Timestamps
  {
    field: "created_at",
    label: "Created At",
    type: "datetime",
    category: "Timestamps",
    sortable: true,
    filterable: true,
  },
];

// Locations Data Source Fields
export const locationFields: ReportFieldDefinition[] = [
  // Basic Info
  {
    field: "id",
    label: "Location ID",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
  },
  {
    field: "name",
    label: "Name",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "code",
    label: "Code",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "description",
    label: "Description",
    type: "string",
    category: "Basic Info",
    sortable: false,
    filterable: true,
  },
  {
    field: "type",
    label: "Type",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "address",
    label: "Address",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
  },

  // Hierarchy
  {
    field: "level",
    label: "Level",
    type: "number",
    category: "Hierarchy",
    sortable: true,
    filterable: true,
  },
  {
    field: "path",
    label: "Path",
    type: "string",
    category: "Hierarchy",
    sortable: true,
    filterable: true,
  },
  {
    field: "parent_id",
    label: "Parent Location",
    type: "enum",
    category: "Hierarchy",
    sortable: true,
    filterable: true,
    relationField: "parent",
    dynamicOptions: "locations",
  },

  // Status
  {
    field: "is_active",
    label: "Active",
    type: "boolean",
    category: "Status",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "sort_order",
    label: "Sort Order",
    type: "number",
    category: "Status",
    sortable: true,
    filterable: true,
  },

  // Timestamps
  {
    field: "created_at",
    label: "Created At",
    type: "datetime",
    category: "Timestamps",
    sortable: true,
    filterable: true,
  },
];

// Workflows Data Source Fields
export const workflowFields: ReportFieldDefinition[] = [
  // Basic Info
  {
    field: "id",
    label: "Workflow ID",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
  },
  {
    field: "name",
    label: "Name",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "code",
    label: "Code",
    type: "string",
    category: "Basic Info",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "description",
    label: "Description",
    type: "string",
    category: "Basic Info",
    sortable: false,
    filterable: true,
  },
  {
    field: "version",
    label: "Version",
    type: "number",
    category: "Basic Info",
    sortable: true,
    filterable: true,
  },

  // Status
  {
    field: "is_active",
    label: "Active",
    type: "boolean",
    category: "Status",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "is_default",
    label: "Default Workflow",
    type: "boolean",
    category: "Status",
    sortable: true,
    filterable: true,
  },

  // Counts
  {
    field: "states_count",
    label: "States Count",
    type: "number",
    category: "Counts",
    sortable: true,
    filterable: true,
    defaultSelected: true,
  },
  {
    field: "transitions_count",
    label: "Transitions Count",
    type: "number",
    category: "Counts",
    sortable: true,
    filterable: true,
  },

  // Matching Config
  {
    field: "priority_min",
    label: "Min Priority",
    type: "number",
    category: "Matching",
    sortable: true,
    filterable: true,
  },
  {
    field: "priority_max",
    label: "Max Priority",
    type: "number",
    category: "Matching",
    sortable: true,
    filterable: true,
  },

  // Creator
  {
    field: "created_by_username",
    label: "Created By",
    type: "string",
    category: "Creator",
    sortable: true,
    filterable: true,
    relationField: "created_by",
    dynamicOptions: "users",
  },

  // Timestamps
  {
    field: "created_at",
    label: "Created At",
    type: "datetime",
    category: "Timestamps",
    sortable: true,
    filterable: true,
  },
  {
    field: "updated_at",
    label: "Updated At",
    type: "datetime",
    category: "Timestamps",
    sortable: true,
    filterable: true,
  },
];

// All Data Sources with their definitions
export const DATA_SOURCES: DataSourceDefinition[] = [
  {
    key: "incidents",
    label: "Incidents",
    description: "Incident tracking and management data",
    icon: "AlertCircle",
    fields: incidentFields,
  },
  {
    key: "requests",
    label: "Requests",
    description: "Request tracking and management data",
    icon: "FileText",
    fields: requestFields,
  },
  {
    key: "action_logs",
    label: "Action Logs",
    description: "System audit trail and user activity",
    icon: "FileText",
    fields: actionLogFields,
  },
  {
    key: "users",
    label: "Users",
    description: "User accounts and profiles",
    icon: "Users",
    fields: userFields,
  },
  {
    key: "departments",
    label: "Departments",
    description: "Organizational department structure",
    icon: "Building2",
    fields: departmentFields,
  },
  {
    key: "locations",
    label: "Locations",
    description: "Physical location hierarchy",
    icon: "MapPin",
    fields: locationFields,
  },
  {
    key: "workflows",
    label: "Workflows",
    description: "Workflow definitions and configurations",
    icon: "GitBranch",
    fields: workflowFields,
  },
];

// Helper function to get fields for a data source
export const getFieldsForDataSource = (
  dataSource: string,
): ReportFieldDefinition[] => {
  const source = DATA_SOURCES.find((ds) => ds.key === dataSource);
  return source?.fields || [];
};

// Helper function to get default selected fields for a data source
export const getDefaultFieldsForDataSource = (
  dataSource: string,
): { field: string; label: string }[] => {
  const fields = getFieldsForDataSource(dataSource);
  return fields
    .filter((f) => f.defaultSelected)
    .map((f) => ({ field: f.field, label: f.label }));
};

// Helper function to get operators for a field type
export const getOperatorsForFieldType = (
  fieldType: string,
): { value: FilterOperator; label: string }[] => {
  return FILTER_OPERATORS_BY_TYPE[fieldType] || FILTER_OPERATORS_BY_TYPE.string;
};

// Helper function to group fields by category
export const groupFieldsByCategory = (
  fields: ReportFieldDefinition[],
): Record<string, ReportFieldDefinition[]> => {
  return fields
    .filter((f) => f?.canBeColumn === true || f.canBeColumn === undefined)
    .reduce(
      (acc, field) => {
        const category = field.category || "Other";
        if (!acc[category]) {
          acc[category] = [];
        }
        acc[category].push(field);
        return acc;
      },
      {} as Record<string, ReportFieldDefinition[]>,
    );
};
