export { AdminDashboard } from './AdminDashboard';
export { UsersPage } from './UsersPage';
export { RolesPage } from './RolesPage';
export { PermissionsPage } from './PermissionsPage';
export { DepartmentsPage } from './DepartmentsPage';
export { DepartmentDetailPage } from './DepartmentDetailPage';
export { LocationsPage } from './LocationsPage';
export { default as LocationMapPage } from './LocationMapPage';
export { ClassificationsPage } from './ClassificationsPage';
export { ActionLogsPage } from './ActionLogsPage';
export { WorkflowsPage } from './WorkflowsPage';
export { WorkflowDesignerPage } from './WorkflowDesignerPage';
export { IncidentsPage } from './IncidentsPage';
export { IncidentCreatePage } from './IncidentCreatePage';
export { IncidentDetailPage } from './IncidentDetailPage';
export { MyIncidentsPage } from './MyIncidentsPage';
export { RequestsPage } from './RequestsPage';
export { RequestDetailPage } from './RequestDetailPage';
export { MyRequestsPage } from './MyRequestsPage';
export { ComplaintsPage } from './ComplaintsPage';
export { ComplaintDetailPage } from './ComplaintDetailPage';
export { QueriesPage } from './QueriesPage';
export { QueryDetailPage } from './QueryDetailPage';
export { SMTPSettingsPage } from './SMTPSettingsPage';
export { ReportBuilderPage } from './ReportBuilderPage';
export { ReportTemplatesPage } from './ReportTemplatesPage';
export { default as ReportTemplatesListPage } from './ReportTemplatesListPage';
export { default as ReportTemplateBuilderPage } from './ReportTemplateBuilderPage';
export { LookupsPage } from './LookupsPage';
export { CallCentrePage } from './CallCentrePage';
export { CallHistory } from './components/CallHistory';
